In [3]:
import torch
torch.__version__

'2.8.0+cu126'

In [4]:
# Creating a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
print(scalar.item())

7


In [7]:
# Create a 1D vector
vector = torch.tensor([1.0,2,3,4])
vector

tensor([1., 2., 3., 4.])

In [8]:
vector.dtype

torch.float32

In [9]:
# Create a 2D tensor/matrix
matrix = torch.tensor([[1,2,3], [4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
print(f'dim={matrix.ndim}, shape={matrix.shape}')

dim=2, shape=torch.Size([2, 3])


In [11]:
# print matrix
print(matrix.numpy())

[[1 2 3]
 [4 5 6]]
