In [2]:
import torch
torch.__version__

'2.8.0+cu126'

In [3]:
# Creating a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
print(scalar.item())

7


In [5]:
# Create a 1D vector
vector = torch.tensor([1.0,2,3,4])
vector

tensor([1., 2., 3., 4.])

In [6]:
vector.dtype

torch.float32

In [7]:
# Create a 2D tensor/matrix
matrix = torch.tensor([[1,2,3], [4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
print(f'dim={matrix.ndim}, shape={matrix.shape}')

dim=2, shape=torch.Size([2, 3])


In [9]:
# print matrix
print(matrix.numpy())

[[1 2 3]
 [4 5 6]]


In [10]:
print(vector.dtype)

torch.float32


In [11]:
# Creating random tensors
randImage = torch.rand(size=(3,4,2))
randImage

tensor([[[0.5080, 0.3764],
         [0.8301, 0.0155],
         [0.2078, 0.1046],
         [0.1851, 0.3009]],

        [[0.8882, 0.8616],
         [0.6688, 0.3355],
         [0.2140, 0.4831],
         [0.2276, 0.8326]],

        [[0.0397, 0.4176],
         [0.9116, 0.9644],
         [0.6266, 0.6712],
         [0.8563, 0.9669]]])

In [12]:
print(f'Shape: {randImage.shape}, ndim: {randImage.ndim}, height: {randImage.shape[0]}, width: {randImage.shape[1]}, depth: {randImage.shape[2]}')

Shape: torch.Size([3, 4, 2]), ndim: 3, height: 3, width: 4, depth: 2


In [13]:
# Creating tensor of 1's
ones = torch.ones(size=(2,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
# Creating tensors of 0's
zeros = torch.zeros(size=(2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
# Creating ones and Zeros to match an existing tensors shape
ones_like = torch.ones_like(zeros)
ones_like

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
zeros_like = torch.zeros_like(ones)
zeros_like

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# arange() and reshape()
aRange = torch.arange(start=0.1, end=5.0, step=0.2)
aRange

tensor([0.1000, 0.3000, 0.5000, 0.7000, 0.9000, 1.1000, 1.3000, 1.5000, 1.7000,
        1.9000, 2.1000, 2.3000, 2.5000, 2.7000, 2.9000, 3.1000, 3.3000, 3.5000,
        3.7000, 3.9000, 4.1000, 4.3000, 4.5000, 4.7000, 4.9000])

In [18]:
matrix = aRange.reshape(shape=(5,5))
matrix

tensor([[0.1000, 0.3000, 0.5000, 0.7000, 0.9000],
        [1.1000, 1.3000, 1.5000, 1.7000, 1.9000],
        [2.1000, 2.3000, 2.5000, 2.7000, 2.9000],
        [3.1000, 3.3000, 3.5000, 3.7000, 3.9000],
        [4.1000, 4.3000, 4.5000, 4.7000, 4.9000]])

In [19]:
import numpy as np

In [20]:
# Creating Tensors from Numpy arrays
npArray = np.arange(1, 21, dtype=np.float32)
npArray

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.], dtype=float32)

In [21]:
# Reahape to (5,4)
npArray = npArray.reshape((5, -1))
print(npArray.shape)
npArray

(5, 4)


array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]], dtype=float32)

In [22]:
torchArray = torch.from_numpy(npArray)
torchArray

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]])

In [23]:
# Casting to integer
torchArray = torchArray.type(torch.int16)
torchArray

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]], dtype=torch.int16)

In [24]:
print(torchArray.numpy())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


## Tensor datatypes

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types). Some are specific for CPU and some are better for GPU. Getting to know which is which can take some time.

Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`. This is referred to as "32-bit floating point". But there are also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`). And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.


In [25]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.,6.,9.],
                               dtype = None, # Defaults to None which is float32
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False # If True, operations performed on the Tensor are recorded
                               )
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [26]:
float_16_tensor = torch.tensor([3.,6.,9.],
                               dtype = torch.float16)
float_16_tensor.dtype

torch.float16

## Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

## Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors. A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

In [27]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor1 = tensor + 10
tensor1

tensor([11, 12, 13])

In [28]:
# Multiply by 10
tensor2 = tensor * 10
tensor2

tensor([10, 20, 30])

In [29]:
tensor - 10

tensor([-9, -8, -7])

PyTorch also has a bunch of built-in functions like [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) (short for multiplication) and [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) to perform basic operations.

In [30]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [31]:
# Element wise multiplication
print(tensor,'*',tensor)
print('Equals:', tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) method.



In [32]:
A = torch.arange(1,7, dtype=torch.float32).reshape((3,-1))

In [33]:
B = torch.rand((2,4))
print(f'B={B}\n shape = {B.shape}')

B=tensor([[0.4780, 0.8447, 0.1513, 0.4759],
        [0.0165, 0.7549, 0.7840, 0.9330]])
 shape = torch.Size([2, 4])


In [34]:
torch.matmul(A,B)

tensor([[0.5110, 2.3545, 1.7194, 2.3419],
        [1.4999, 5.5536, 3.5901, 5.1596],
        [2.4888, 8.7527, 5.4608, 7.9774]])

In [35]:
A.matmul(B)

tensor([[0.5110, 2.3545, 1.7194, 2.3419],
        [1.4999, 5.5536, 3.5901, 5.1596],
        [2.4888, 8.7527, 5.4608, 7.9774]])

In [36]:
A@B

tensor([[0.5110, 2.3545, 1.7194, 2.3419],
        [1.4999, 5.5536, 3.5901, 5.1596],
        [2.4888, 8.7527, 5.4608, 7.9774]])

### Linear Layer

Neural networks are full of matrix multiplications and dot products.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `W`.

$$
y = x\cdot W + b
$$


In [37]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [39]:
# Setting reproducibility
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, #matches inner dimension of i/p
                         out_features=6) # describes outer value

x = tensor_A
output = linear(x)
print(f'Input Shape: {x.shape}')
print(f'Output: {output}\n Output Shape: {output.shape}')

Input Shape: torch.Size([3, 2])
Output: tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
 Output Shape: torch.Size([3, 6])


In [41]:
# Aggregation
print(f'Minimum: {x.min()}')
print(f'Maximum: {x.max()}')
print(f'Mean: {x.type(torch.float32).mean()}') # Will only work with float type
print(f'Sum: {x.sum()}')

Minimum: 1.0
Maximum: 6.0
Mean: 3.5
Sum: 21.0


### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |


**<span style="color:red">Exercise 1</span>:** Write the code to
- Create a random 2D tensor X with dimension [32,10] (i.e., batch size = 32 and #features = 10).
- Create a random weight matrix W with dimension [10,2] and random bias b with dimension [1,2].
- Do the computation y = XW + b and pred_probs = softmax(y).

In [48]:
X = torch.rand(size=(32,10))
W = torch.rand(size=(10,2))
b = torch.rand(size=(1,2))

y = X@W + b
print(f'y={y.numpy()}')
pred_probs = torch.softmax(y, dim=1)

print(f'Pred probs= {pred_probs.numpy()}')

y=[[2.7158136 3.1059742]
 [1.9455227 1.950945 ]
 [2.2687693 2.7530847]
 [2.1171541 2.6586933]
 [2.7801685 3.3753853]
 [2.7384548 3.5310793]
 [2.090353  2.8650126]
 [2.4476333 3.127367 ]
 [1.9348081 2.658307 ]
 [2.3338375 2.5274792]
 [1.8243448 2.6878157]
 [1.3026775 1.6044418]
 [2.0570652 2.619309 ]
 [2.2376227 2.5947099]
 [1.8699113 2.5711565]
 [2.4711275 2.5468068]
 [1.6449343 2.289967 ]
 [1.6474295 1.9777083]
 [1.3114891 1.5470577]
 [1.9449764 2.456386 ]
 [2.0435362 2.0215316]
 [1.7809302 2.6122637]
 [1.3519192 2.318447 ]
 [1.1452692 1.8440614]
 [1.7949165 2.0732946]
 [2.169024  2.6357014]
 [2.2256522 2.6624074]
 [1.7749287 2.4603686]
 [2.634297  3.1469984]
 [2.1651063 3.0265007]
 [1.6014045 2.0664473]
 [1.7926021 2.30229  ]]
Pred probs= [[0.40367866 0.59632134]
 [0.4986444  0.5013556 ]
 [0.38123363 0.61876637]
 [0.36782962 0.63217044]
 [0.35543877 0.6445612 ]
 [0.31160542 0.68839455]
 [0.31547198 0.684528  ]
 [0.33632073 0.66367924]
 [0.32662296 0.67337704]
 [0.45174026 0.5482597 ]